# driveMaterial can be any Material.
# List of all Materials: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html

# delay can be any delay of: SECOND, MINUTE, HOUR

machines:
  calculator:
    enabled: true
    driveMaterial: REDSTONE
    delay: SECOND
    materialPerDelay: 1
  bag:
    enabled: true
    driveMaterial: COAL
    delayInBag: SECOND
    materialPerDelayInBag: 1
    delayOutsideBag: MINUTE
    materialPerDelayOutsideBag: 1
  itemchanger:
    enabled: true
    1:
      from: GOLD_INGOT 2
      to: DIAMOND 1
      delay: SECOND
      delayTime: 10
      materialPerDelay: 4
      driveMaterial: COAL
    2:
      from: DIAMOND 1
      to: EMERALD 1
      delay: SECOND
      delayTime: 10
      materialPerDelay: 2
      driveMaterial: COAL