name: MarianDCrafter-t2
main: com.tenjava.entries.MarianDCrafter.t2.TenJava
version: '${project.version}'

commands:
  calculator:
    description: Opens up a calculator view. (Costs something)
  bag:
    description: Opens the bag. (Costs something)

permissions:
  machines.*:
    description: All Machines permissions.
    default: op
    children:
      machines.calculator: true
  machines.calculator:
    description: Allows you to execute the calculator command.
    default: op
  machines.bag:
    description: Allows you to execute the bag command.
    default: op